name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    name: Build for ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        includes:
          - os: macos-latest
            target: x86_64-apple-darwin
            filename: darwin-amd64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            filename: linux-amd64

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
        env:
          TARGET: ${{ matrix.target }}
          FILENAME: ${{ matrix.filename }}
