name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
      - uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
