on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            name: windows-amd64
          - target: x86_64-unknown-linux-musl
            name: linux-amd64
          - target: x86_64-apple-darwin
            name: darwin-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Compile and release
        uses: rust-build/rust-build.action@6694d4a74d687379a2e9780def73228afa87dae8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          ARCHIVE_TYPES: tar.gz
          NAME: ${{ matrix.name }}
